### ISSUE TITLE
SP410 Negative image

### ISSUE THREAD

**Issue by cinghialino** [thorrak/rpi-tspl-cups-driver#3]
I have installed your repo following the instructions provided (at first I was getting filter failed, then I went to this issues to install Proski). After a bit of testing I was able to have the printer print. 

Problem is that the image is in negative (the test print comes out as a black label with the "Printer test page" and "Debian" in white.
I tried to set the "Default options" in CUPS to Effectives>Negative Image>Yes but to no improvement.

Any ideas?

Thanks.

**Comment by thorrak** [comment]
Assuming you're using my code, you will need to revert [this change](https://github.com/OpenPrinting/cups/commit/b46d55547dc2a2cc492b71ddc891e2f16af6d681).

**Comment by cinghialino** [comment]
thanks, i'm willing to try it but where do I find that file?

**Comment by thorrak** [comment]
I have the code modifications I made linked in the readme to this (binary) repo. You’ll need to make the modifications and recompile it yourself, unfortunately.

**Comment by cinghialino** [comment]
I understand. Back to square one for me. Thanks anyway.
